#!/usr/bin/env python3 -tt


def create_exfiltration_xml(sd):
    with open(sd + "t1020.xml", "w") as t1020xml:  # undetectable
        t1020xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1020: Automated Exfiltration</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1020xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1020xml.write(
            '| search id="T1020" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1020xml.write(
            '<html depends="$it_tok$" src="t1020.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1030.xml", "w") as t1030xml:  # undetectable
        t1030xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1030: Data Transfer Size Limits</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1030xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1030xml.write(
            '| search id="T1030" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1030xml.write(
            '<html depends="$it_tok$" src="t1030.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1048.xml", "w") as t1048xml:
        t1048xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1048: Exfiltration Over Alternative Protocol</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1048xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1048xml.write(
            '<html depends="$it_tok$" src="t1048.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1048_memory_panel$">\n      <table>\n        '
        )
        t1048xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ logtype=memory `non-standard_ports` "
        )
        t1048xml.write(
            '| stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1048_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1048_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1048_timeline_panel$">\n      <table>\n        '
        )
        t1048xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1048xml.write(
            '| search id="T1048" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1048_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1048_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1048_browser_panel$">\n      <table>\n        '
        )
        t1048xml.write(
            "<title>Browser activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ logtype=browser "
        )
        t1048xml.write(
            '| `browser_name` | `browser_domain` | table index host logtype LastWriteTime browser Domain url title Profile Protocol | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1048_browser_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1048_browser_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1048xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1041.xml", "w") as t1041xml:
        t1041xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1041: Exfiltration Over C2 Channel</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1041xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1041xml.write(
            '| search id="T1041" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1041xml.write(
            '<html depends="$it_tok$" src="t1041.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1041_memory_panel$">\n      <table>\n        '
        )
        t1041xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory `standard_ports` | `MITRE_lookup` "
        )
        t1041xml.write(
            '| search id="T1041" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1041_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1041_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1041_browser_panel$">\n      <table>\n        '
        )
        t1041xml.write(
            "<title>Browser activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ logtype=browser | `MITRE_lookup` "
        )
        t1041xml.write(
            '| `browser_name` | `browser_domain` | table index host logtype LastWriteTime browser Domain url title Profile Protocol | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1041_browser_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1041_browser_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1041xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1011.xml", "w") as t1011xml:
        t1011xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1011: Exfiltration Over Other Network Medium</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1011xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1011xml.write(
            '| search id="T1011" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1011xml.write(
            '<html depends="$it_tok$" src="t1011.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1011_memory_panel$">\n      <table>\n        '
        )
        t1011xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory `standard_ports` | `MITRE_lookup` "
        )
        t1011xml.write(
            '| search id="T1011" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1011_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1011_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1011_timeline_panel$">\n      <table>\n        '
        )
        t1011xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1011xml.write(
            '| search id="T1011" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1011_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1011_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1011_unix_log_panel$">\n      <table>\n        '
        )
        t1011xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1011xml.write(
            '| search id="T1011" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1011_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1011_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1011_unix_svc_panel$">\n      <table>\n        '
        )
        t1011xml.write(
            "<title>Unix service activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=service | `MITRE_lookup` "
        )
        t1011xml.write(
            '| search id="T1011" | table index host mitre_id mitre_technique Service Description | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1011_unix_svc_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1011_unix_svc_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1011_plist_panel$">$4\n      <table>\n        '
        )
        t1011xml.write(
            "<title>Plist entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=plist | `MITRE_lookup` "
        )
        t1011xml.write(
            '| search id="T1011" | table index host mitre_id mitre_technique Plist KeepAlive POSIXSpawnType "ProgramArguments{}"</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1011_plist_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1011_plist_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1011xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1052.xml", "w") as t1052xml:
        t1052xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1052: Exfiltration Over Physical Medium</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1052xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1052xml.write(
            '| search id="T1052" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1052xml.write(
            '<html depends="$it_tok$" src="t1052.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1052_timeline_panel$">\n      <table>\n        '
        )
        t1052xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1052xml.write(
            '| search id="t1052" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1052_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1052_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1052_usb_panel$">\n      <table>\n        '
        )
        t1052xml.write(
            '<title>USB activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique=$mitre_tok$ `usb_out`</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1052_usb_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1052_usb_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1052xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1567.xml", "w") as t1567xml:
        t1567xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1567: Exfiltration Over Web Service</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1567xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1567xml.write(
            '| search id="T1567" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1567xml.write(
            '<html depends="$it_tok$" src="t1567.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1567_memory_panel$">\n      <table>\n        '
        )
        t1567xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory `standard_ports` | `MITRE_lookup` "
        )
        t1567xml.write(
            '| search id="T1567" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1567_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1567_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1567_timeline_panel$">\n      <table>\n        '
        )
        t1567xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1567xml.write(
            '| search id="T1567" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1567_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1567_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1567_journal_panel$">\n      <table>\n        '
        )
        t1567xml.write(
            "<title>Windows-based file activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=journal | `MITRE_lookup` "
        )
        t1567xml.write(
            '| search id="T1567" | `make_fileinfo` | table index host mitre_id mitre_technique LastWriteTime Filepath Filename Fileext</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1567_journal_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1567_journal_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1567_unix_log_panel$">\n      <table>\n        '
        )
        t1567xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1567xml.write(
            '| search id="T1567" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1567_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1567_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1567_browser_panel$">\n      <table>\n        '
        )
        t1567xml.write(
            "<title>Browser activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ logtype=browser | `MITRE_lookup` "
        )
        t1567xml.write(
            '| `browser_name` | `browser_domain` | table index host logtype LastWriteTime browser Domain url title Profile Protocol | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1567_browser_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1567_browser_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1567_audit_panel$">\n      <table>\n        '
        )
        t1567xml.write(
            "<title>Audit file entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=audit | `MITRE_lookup` "
        )
        t1567xml.write(
            '| search id="T1567" | `audit_assignments` | table index host mitre_id mitre_technique audit_file LastAccessTime Filename Filesize Entropy SHA256 | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1567_audit_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1567_audit_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1567xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1029.xml", "w") as t1029xml:  # undetectable
        t1029xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1029: Scheduled Transfer</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1029xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1029xml.write(
            '| search id="T1029" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1029xml.write(
            '<html depends="$it_tok$" src="t1029.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1537.xml", "w") as t1537xml:
        t1537xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1537: Transfer Data to Cloud Account</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1537xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1537xml.write(
            '| search id="T1537" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1537xml.write(
            '<html depends="$it_tok$" src="t1537.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_memory_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory `standard_ports` | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_timeline_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_journal_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Windows-based file activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=journal | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" | `make_fileinfo` | table index host mitre_id mitre_technique LastWriteTime Filepath Filename Fileext</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_journal_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_journal_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_evt_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Windows event log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=evt | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" | eval TargetSids=mvappend(TargetSid,TargetUserSid) | table SystemTime host Computer Channel EventID LogonType SubjectUserName SubjectUserSid DisplayName WorkstationName TargetSids</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_evt_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_evt_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_reg_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Registry activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=registry | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" RegistryKey=* | table index host mitre_id mitre_technique Plugin AccountProfile RegistryHive RegistryKey CommandParameters</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_reg_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_reg_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_shim_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Evidence of execution</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=shimcache | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" | table index host mitre_id mitre_technique LastWriteTime ProcessPath ProcessName</query>\n          <earliest>0</earliest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_shim_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_shim_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_unix_log_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_unix_svc_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Unix service activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=service | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" | table index host mitre_id mitre_technique Service Description | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_unix_svc_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_unix_svc_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_audit_panel$">\n      <table>\n        '
        )
        t1537xml.write(
            "<title>Audit file entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=audit | `MITRE_lookup` "
        )
        t1537xml.write(
            '| search id="T1537" | `audit_assignments` | table index host mitre_id mitre_technique audit_file LastAccessTime Filename Filesize Entropy SHA256 | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_audit_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_audit_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1537_browser_panel$">\n      <table>\n      '
        )
        t1537xml.write(
            '<title>Browser activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ logtype=browser (onedrive OR 1drv OR azure OR icloud OR cloudrive OR dropbox OR "drive.google" OR fileshare OR mediafire OR zippyshare OR megaupload) '
        )
        t1537xml.write(
            '| `browser_name` | `browser_domain` | table index host logtype LastWriteTime browser Domain url title Profile Protocol | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1537_browser_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1537_browser_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1537xml.write("</panel>\n  </row>\n</form>")
