#!/usr/bin/env python3 -tt


def create_impact_xml(sd):
    with open(sd + "t1531.xml", "w") as t1531xml:
        t1531xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1531: Account Access Removal</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1531xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1531xml.write(
            '| search id="T1531" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1531xml.write(
            '<html depends="$it_tok$" src="t1531.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1531_evt_panel$">\n      <table>\n        '
        )
        t1531xml.write(
            "<title>Windows event log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=evt | `MITRE_lookup` "
        )
        t1531xml.write(
            '| search id="T1531" | eval TargetSids=mvappend(TargetSid,TargetUserSid) | table SystemTime host Computer Channel EventID LogonType SubjectUserName SubjectUserSid DisplayName WorkstationName TargetSids</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1531_evt_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1531_evt_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1531_unix_log_panel$">\n      <table>\n        '
        )
        t1531xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1531xml.write(
            '| search id="T1531" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1531_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1531_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1531xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1485.xml", "w") as t1485xml:
        t1485xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1485: Data Destruction</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1485xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1485xml.write(
            '| search id="T1485" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1485xml.write(
            '<html depends="$it_tok$" src="t1485.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1485_memory_panel$">\n      <table>\n        '
        )
        t1485xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory | `MITRE_lookup` "
        )
        t1485xml.write(
            '| search id="T1485" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1485_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1485_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1485_journal_panel$">\n      <table>\n        '
        )
        t1485xml.write(
            "<title>Windows-based file activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=journal | `MITRE_lookup` "
        )
        t1485xml.write(
            '| search id="T1485" | `make_fileinfo` | table index host mitre_id mitre_technique LastWriteTime Filepath Filename Fileext</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1485_journal_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1485_journal_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1485_unix_log_panel$">\n      <table>\n        '
        )
        t1485xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1485xml.write(
            '| search id="T1485" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1485_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1485_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1485_plist_panel$">$4\n      <table>\n        '
        )
        t1485xml.write(
            "<title>Plist entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=plist | `MITRE_lookup` "
        )
        t1485xml.write(
            '| search id="T1485" | table index host mitre_id mitre_technique Plist KeepAlive POSIXSpawnType "ProgramArguments{}"</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1485_plist_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1485_plist_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1485_audit_panel$">\n      <table>\n        '
        )
        t1485xml.write(
            "<title>Audit file entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=audit | `MITRE_lookup` "
        )
        t1485xml.write(
            '| search id="T1485" | `audit_assignments` | table index host mitre_id mitre_technique audit_file LastAccessTime Filename Filesize Entropy SHA256 | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1485_audit_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1485_audit_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1485xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1486.xml", "w") as t1486xml:  # undetectable
        t1486xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1486: Data Encrypted for Impact</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1486xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1486xml.write(
            '| search id="T1486" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1486xml.write(
            '<html depends="$it_tok$" src="t1486.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1565.xml", "w") as t1565xml:  # undetectable
        t1565xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1565: Data Manipulation</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1565xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1565xml.write(
            '| search id="T1565" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1565xml.write(
            '<html depends="$it_tok$" src="t1565.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1491.xml", "w") as t1491xml:  # undetectable
        t1491xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1491: Defacement</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1491xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1491xml.write(
            '| search id="T1491" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1491xml.write(
            '<html depends="$it_tok$" src="t1491.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1561.xml", "w") as t1561xml:  # undetectable
        t1561xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1561: Disk Wipe</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1561xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1561xml.write(
            '| search id="T1561" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1561xml.write(
            '<html depends="$it_tok$" src="t1561.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1499.xml", "w") as t1499xml:  # undetectable
        t1499xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1499: Endpoint Denial of Service</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1499xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1499xml.write(
            '| search id="T1499" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1499xml.write(
            '<html depends="$it_tok$" src="t1499.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1495.xml", "w") as t1495xml:  # undetectable
        t1495xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1495: Firmware Corruption</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1495xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1495xml.write(
            '| search id="T1495" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1495xml.write(
            '<html depends="$it_tok$" src="t1495.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1490.xml", "w") as t1490xml:
        t1490xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1490: Inhibit System Recovery</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1490xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1490xml.write(
            '| search id="T1490" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1490xml.write(
            '<html depends="$it_tok$" src="t1490.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1490_memory_panel$">\n      <table>\n        '
        )
        t1490xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory | `MITRE_lookup` "
        )
        t1490xml.write(
            '| search id="T1490" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1490_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1490_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1490_timeline_panel$">\n      <table>\n        '
        )
        t1490xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1490xml.write(
            '| search id="T1490" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1490_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1490_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1490_reg_panel$">\n      <table>\n        '
        )
        t1490xml.write(
            "<title>Registry activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=registry | `MITRE_lookup` "
        )
        t1490xml.write(
            '| search id="T1490" RegistryKey=* | table index host mitre_id mitre_technique Plugin AccountProfile RegistryHive RegistryKey CommandParameters</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1490_reg_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1490_reg_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1490_evt_panel$">\n      <table>\n        '
        )
        t1490xml.write(
            "<title>Windows event log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=evt | `MITRE_lookup` "
        )
        t1490xml.write(
            '| search id="T1490" | eval TargetSids=mvappend(TargetSid,TargetUserSid) | table SystemTime host Computer Channel EventID LogonType SubjectUserName SubjectUserSid DisplayName WorkstationName TargetSids</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1490_evt_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1490_evt_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1490_unix_log_panel$">\n      <table>\n        '
        )
        t1490xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1490xml.write(
            '| search id="T1490" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1490_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1490_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1490xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1498.xml", "w") as t1498xml:  # no events available
        t1498xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1498: Network Denial of Service</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1498xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1498xml.write(
            '| search id="T1498" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1498xml.write(
            '<html depends="$it_tok$" src="t1498.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1496.xml", "w") as t1496xml:  # no events available
        t1496xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1496: Resource Hijacking</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1496xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1496xml.write(
            '| search id="T1496" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1496xml.write(
            '<html depends="$it_tok$" src="t1496.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1489.xml", "w") as t1489xml:
        t1489xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1486: Service Stop</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1489xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1489xml.write(
            '| search id="T1489" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1489xml.write(
            '<html depends="$it_tok$" src="t1489.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_memory_panel$">\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_timeline_panel$">\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_journal_panel$">\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Windows-based file activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=journal | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | `make_fileinfo` | table index host mitre_id mitre_technique LastWriteTime Filepath Filename Fileext</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_journal_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_journal_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_evt_panel$">\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Windows event log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=evt | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | eval TargetSids=mvappend(TargetSid,TargetUserSid) | table SystemTime host Computer Channel EventID LogonType SubjectUserName SubjectUserSid DisplayName WorkstationName TargetSids</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_evt_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_evt_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_shim_panel$">\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Evidence of execution</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=shimcache | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | table index host mitre_id mitre_technique LastWriteTime ProcessPath ProcessName</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_shim_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_shim_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_unix_log_panel$">\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_unix_svc_panel$">\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Unix service activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=service | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | table index host mitre_id mitre_technique Service Description | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_unix_svc_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_unix_svc_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_plist_panel$">$4\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Plist entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=plist | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | table index host mitre_id mitre_technique Plist KeepAlive POSIXSpawnType "ProgramArguments{}"</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_plist_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_plist_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1489_audit_panel$">\n      <table>\n        '
        )
        t1489xml.write(
            "<title>Audit file entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=audit | `MITRE_lookup` "
        )
        t1489xml.write(
            '| search id="T1489" | `audit_assignments` | table index host mitre_id mitre_technique audit_file LastAccessTime Filename Filesize Entropy SHA256 | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1489_audit_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1489_audit_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1489xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1529.xml", "w") as t1529xml:
        t1529xml.write(
            '<form stylesheet="mitre.css" theme="dark">\n  <label>T1529: System Shutdown/Reboot</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1529xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <populatingSearch fieldForLabel="it" fieldForValue="it">| gentimes start=-1 | eval it="Toggle MITRE Information"</populatingSearch>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1529xml.write(
            '| search id="T1529" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-7d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1529xml.write(
            '<html depends="$it_tok$" src="t1529.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1529_memory_panel$">\n      <table>\n        '
        )
        t1529xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory | `MITRE_lookup` "
        )
        t1529xml.write(
            '| search id="T1529" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1529_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1529_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1529_timeline_panel$">\n      <table>\n        '
        )
        t1529xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1529xml.write(
            '| search id="T1529" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1529_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1529_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1529_evt_panel$">\n      <table>\n        '
        )
        t1529xml.write(
            "<title>Windows event log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=evt | `MITRE_lookup` "
        )
        t1529xml.write(
            '| search id="T1529" | eval TargetSids=mvappend(TargetSid,TargetUserSid) | table SystemTime host Computer Channel EventID LogonType SubjectUserName SubjectUserSid DisplayName WorkstationName TargetSids</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1529_evt_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1529_evt_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1529_unix_log_panel$">\n      <table>\n        '
        )
        t1529xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1529xml.write(
            '| search id="T1529" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1529_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1529_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1529xml.write("</panel>\n  </row>\n</form>")
