#!/usr/bin/env python3 -tt


def create_initial_access_xml(sd):
    with open(sd + "t1189.xml", "w") as t1189xml:
        t1189xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1189: Drive-by Compromise</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1189xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1189xml.write(
            '| search id="T1189" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1189xml.write(
            '<html depends="$it_tok$" src="t1189.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1189_memory_panel$">\n      <table>\n        '
        )
        t1189xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory `standard_ports` | `MITRE_lookup` "
        )
        t1189xml.write(
            '| search id="T1189" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1189_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1189_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1189_browser_panel$">\n      <table>\n        '
        )
        t1189xml.write(
            "<title>Browser activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ logtype=browser | `MITRE_lookup` "
        )
        t1189xml.write(
            '| `browser_name` | `browser_domain` | table index host logtype LastWriteTime browser Domain url title Profile Protocol | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1189_browser_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1189_browser_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1189xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1190.xml", "w") as t1190xml:  # undetectable
        t1190xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1190: Exploit Public-Facing Application</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1190xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1190xml.write(
            '| search id="T1190" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1190xml.write(
            '<html depends="$it_tok$" src="t1190.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1133.xml", "w") as t1133xml:
        t1133xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1133: External Remote Services</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1133xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1133xml.write(
            '| search id="T1133" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1133xml.write(
            '<html depends="$it_tok$" src="t1133.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1133_memory_panel$">\n      <table>\n        '
        )
        t1133xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory `standard_ports` | `MITRE_lookup` "
        )
        t1133xml.write(
            '| search id="T1133" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1133_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1133_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1133xml.write("\n    </panel>\n  </row>\n</form>")
    with open(sd + "t1200.xml", "w") as t1200xml:
        t1200xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1200: Hardware Additions</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1200xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1200xml.write(
            '| search id="T1200" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1200xml.write(
            '<html depends="$it_tok$" src="t1200.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1200_usb_panel$">\n      <table>\n        '
        )
        t1200xml.write(
            '<title>USB activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique=$mitre_tok$ `usb_out`</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1200_usb_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1200_usb_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1200xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1566.xml", "w") as t1566xml:
        t1566xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1566: Phishing</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1566xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1566xml.write(
            '| search id="T1203" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1566xml.write(
            '<html depends="$it_tok$" src="t1203.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1566_journal_panel$">\n      <table>\n        '
        )
        t1566xml.write(
            "<title>Windows-based file activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=journal | `MITRE_lookup` "
        )
        t1566xml.write(
            '| search id="T1203" | `make_fileinfo` | table index host mitre_id mitre_technique LastWriteTime Filepath Filename Fileext</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1566_journal_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1566_journal_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1566_unix_log_panel$">\n      <table>\n      '
        )
        t1566xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1566xml.write(
            '| search id="T1203" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1566_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1566_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1566_audit_panel$">\n      <table>\n     '
        )
        t1566xml.write(
            "<title>Audit file entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=audit | `MITRE_lookup` "
        )
        t1566xml.write(
            '| search id="T1203" | `audit_assignments` | table index host mitre_id mitre_technique audit_file LastAccessTime Filename Filesize Entropy SHA256 | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1566_audit_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1566_audit_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1566xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1091.xml", "w") as t1091xml:
        t1091xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1091: Replication Through Removable Media</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1091xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1091xml.write(
            '| search id="T1091" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1091xml.write(
            '<html depends="$it_tok$" src="t1091.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1091_usb_panel$">\n      <table>\n        '
        )
        t1091xml.write(
            '<title>USB activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique=$mitre_tok$ `usb_out`</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1091_usb_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1091_usb_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1091xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1195.xml", "w") as t1195xml:  # undetectable
        t1195xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1195: Supply Chain Compromise</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1195xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1195xml.write(
            '| search id="T1195" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1195xml.write(
            '<html depends="$it_tok$" src="t1195.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1199.xml", "w") as t1199xml:  # undetectable
        t1199xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1199: Trusted Relationship</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1199xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1199xml.write(
            '| search id="T1199" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1199xml.write(
            '<html depends="$it_tok$" src="t1199.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1078.xml", "w") as t1078xml:
        t1078xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1078: Valid Accounts</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1078xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1078xml.write(
            '| search id="T1078" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1078xml.write(
            '<html depends="$it_tok$" src="t1078.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1078_memory_panel$">\n      <table>\n        '
        )
        t1078xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory `standard_ports` | `MITRE_lookup` "
        )
        t1078xml.write(
            '| search id="T1078" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1078_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1078_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1078xml.write("\n    </panel>\n  </row>\n</form>")
