#!/usr/bin/env python3 -tt


def create_privilege_escalation_xml(sd):
    with open(sd + "t1548.xml", "w") as t1548xml:
        t1548xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1548: Abuse Elevation Control Mechanism</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1548xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1548xml.write(
            '| search id="T1548" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1548xml.write(
            '<html depends="$it_tok$" src="t1548.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_memory_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_timeline_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_journal_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Windows-based file activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=journal | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" | `make_fileinfo` | table index host mitre_id mitre_technique LastWriteTime Filepath Filename Fileext</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_journal_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_journal_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_evt_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Windows event log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=evt | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" | eval TargetSids=mvappend(TargetSid,TargetUserSid) | table SystemTime host Computer Channel EventID LogonType SubjectUserName SubjectUserSid DisplayName WorkstationName TargetSids</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_evt_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_evt_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_reg_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Registry activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=registry | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" RegistryKey=* | table index host mitre_id mitre_technique Plugin AccountProfile RegistryHive RegistryKey CommandParameters</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_reg_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_reg_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_shim_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Evidence of execution</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=shimcache | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" | table index host mitre_id mitre_technique LastWriteTime ProcessPath ProcessName</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_shim_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_shim_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_unix_log_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_unix_svc_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Unix service activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=service | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" | table index host mitre_id mitre_technique Service Description | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_unix_svc_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_unix_svc_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1548_audit_panel$">\n      <table>\n        '
        )
        t1548xml.write(
            "<title>Audit file entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=audit | `MITRE_lookup` "
        )
        t1548xml.write(
            '| search id="T1548" | `audit_assignments` | table index host mitre_id mitre_technique audit_file LastAccessTime Filename Filesize Entropy SHA256 | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1548_audit_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1548_audit_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1548xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1134.xml", "w") as t1134xml:
        t1134xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1134: Access Token Manipulation</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1134xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1134xml.write(
            '| search id="T1134" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1134xml.write(
            '<html depends="$it_tok$" src="t1134.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1134_memory_panel$">\n      <table>\n        '
        )
        t1134xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory | `MITRE_lookup` "
        )
        t1134xml.write(
            '| search id="T1134" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1134_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1134_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1134xml.write("\n    </panel>\n  </row>\n</form>")
    with open(sd + "t1484.xml", "w") as t1484xml:
        t1484xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1484: Group Policy Modification</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1484xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1484xml.write(
            '| search id="T1484" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1484xml.write(
            '<html depends="$it_tok$" src="t1484.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1484_memory_panel$">\n      <table>\n        '
        )
        t1484xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory | `MITRE_lookup` "
        )
        t1484xml.write(
            '| search id="T1484" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1484_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1484_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1484_timeline_panel$">\n      <table>\n        '
        )
        t1484xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1484xml.write(
            '| search id="T1484" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1484_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1484_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1484_journal_panel$">\n      <table>\n        '
        )
        t1484xml.write(
            "<title>Windows-based file activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=journal | `MITRE_lookup` "
        )
        t1484xml.write(
            '| search id="T1484" | `make_fileinfo` | table index host mitre_id mitre_technique LastWriteTime Filepath Filename Fileext</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1484_journal_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1484_journal_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1484_evt_panel$">\n      <table>\n        '
        )
        t1484xml.write(
            "<title>Windows event log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=evt | `MITRE_lookup` "
        )
        t1484xml.write(
            '| search id="T1484" | eval TargetSids=mvappend(TargetSid,TargetUserSid) | table SystemTime host Computer Channel EventID LogonType SubjectUserName SubjectUserSid DisplayName WorkstationName TargetSids</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1484_evt_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1484_evt_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1484_audit_panel$">\n      <table>\n        '
        )
        t1484xml.write(
            "<title>Audit file entries</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=audit | `MITRE_lookup` "
        )
        t1484xml.write(
            '| search id="T1484" | `audit_assignments` | table index host mitre_id mitre_technique audit_file LastAccessTime Filename Filesize Entropy SHA256 | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1484_audit_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1484_audit_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1484xml.write("</panel>\n  </row>\n</form>")
    with open(sd + "t1611.xml", "w") as t1611xml:  # undetectable
        t1611xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1611: Escape to Host</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1611xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1611xml.write(
            '| search id="T1611" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1611xml.write(
            '<html depends="$it_tok$" src="t1611.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1068.xml", "w") as t1068xml:  # undetectable
        t1068xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1068: Exploitation for Privilege Escalation</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1068xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1068xml.write(
            '| search id="T1068" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1068xml.write(
            '<html depends="$it_tok$" src="t1068.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel>\n      <html src="na.html"/>\n    </panel>\n  </row>\n</form>\n'
        )
    with open(sd + "t1055.xml", "w") as t1055xml:
        t1055xml.write(
            '<form version="1.1" stylesheet="mitre.css" theme="dark">\n  <label>T1055: Process Injection</label>\n  <description>If a dashboard panel is not showing, no events exist which satisify that log source for this technique.</description>\n  '
        )
        t1055xml.write(
            '<search id="base">\n    <query>index=* | dedup index | search index=$case_tok$ host=$host_tok$ | table index host</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="mitre_base">\n    <query>index=$case_tok$ host=$host_tok$ mitre_technique!=-</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <search id="dash">\n    <query>| rest /servicesNS/-/-/data/ui/views | search "eai:acl.app"=elrond label=T*</query>\n    <earliest>$time_tok.earliest$</earliest>\n    <latest>$time_tok.latest$</latest>\n  </search>\n  <fieldset submitButton="false">\n    <input type="checkbox" token="it_tok">\n      <label></label>\n      <search>\n        <query><![CDATA[| gentimes start=-1 | eval it="Toggle MITRE Information"]]></query>\n      </search>\n      <fieldForLabel>it</fieldForLabel>\n      <fieldForValue>it</fieldForValue>\n    </input>\n    <input type="dropdown" token="case_tok" searchWhenChanged="true">\n      <label>Select a Case:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>index</fieldForLabel>\n      <fieldForValue>index</fieldForValue>\n      <search base="base">\n        <query>| dedup index | sort index</query>\n      </search>\n    </input>\n    <input type="dropdown" token="host_tok" searchWhenChanged="true">\n      <label>Select a Host:</label>\n      <choice value="*">All</choice>\n      <default>*</default>\n      <initialValue>*</initialValue>\n      <fieldForLabel>host</fieldForLabel>\n      <fieldForValue>host</fieldForValue>\n      <search base="base">\n        <query>| dedup host | sort host</query>\n      </search>\n    </input>\n    <input type="dropdown" token="mitre_tok" searchWhenChanged="true">\n      <label>Select MITRE Technique:</label>\n      <choice value="*">All</choice>\n      <fieldForLabel>mitre_technique</fieldForLabel>\n      <fieldForValue>mitre_technique</fieldForValue>\n      <search base="mitre_base">\n        <query>| `MITRE_lookup` '
        )
        t1055xml.write(
            '| search id="T1055" | stats count BY mitre_id mitre_technique | sort mitre_id | fields - mitre_id</query>\n      </search>\n      <default>*</default>\n      <prefix>"*</prefix>\n      <suffix>"</suffix>\n      <initialValue>*</initialValue>\n    </input>\n    <input type="time" token="time_tok" searchWhenChanged="true">\n      <label>Select a Time Range:</label>\n      <default>\n        <earliest>-1d@h</earliest>\n        <latest></latest>\n      </default>\n    </input>\n  </fieldset>\n  <row>\n    <panel>\n      '
        )
        t1055xml.write(
            '<html depends="$it_tok$" src="t1055.html"/>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1055_memory_panel$">\n      <table>\n        '
        )
        t1055xml.write(
            "<title>Volatile activity in memory</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=memory | `MITRE_lookup` "
        )
        t1055xml.write(
            '| search id="T1055" | stats count values(LocalAddress) AS LocalAddresses values(ForeignAddress) AS ForeignAddresses BY host ProcessName PID LocalPort ForeignPort Protocol State | sort -count | table host ProcessName PID LocalAddresses LocalPort ForeignAddresses ForeignPort Protocol State count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1055_memory_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1055_memory_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1055_timeline_panel$">\n      <table>\n        '
        )
        t1055xml.write(
            "<title>Timeline activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=timeline | `MITRE_lookup` "
        )
        t1055xml.write(
            '| search id="T1055" | stats count BY index host mitre_id mitre_technique LastWriteTime source_long Artefact Message | sort 0 -count LastWriteTime | fields - count</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1055_timeline_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1055_timeline_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1055_journal_panel$">\n      <table>\n        '
        )
        t1055xml.write(
            "<title>Windows event log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=evt | `MITRE_lookup` "
        )
        t1055xml.write(
            '| search id="T1055" | eval TargetSids=mvappend(TargetSid,TargetUserSid) | table SystemTime host Computer Channel EventID LogonType SubjectUserName SubjectUserSid DisplayName WorkstationName TargetSids</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1055_evt_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1055_evt_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="refresh.display">progressbar</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1055_unix_log_panel$">\n      <table>\n        '
        )
        t1055xml.write(
            "<title>Unix log activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=log | `MITRE_lookup` "
        )
        t1055xml.write(
            '| search id="T1055" | table index host mitre_id mitre_technique LastWriteTime Device Service PID Message | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1055_unix_log_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1055_unix_log_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    </panel>\n  </row>\n  <row>\n    <panel depends="$t1055_unix_svc_panel$">\n      <table>\n        '
        )
        t1055xml.write(
            "<title>Unix service activity</title>\n        <search>\n          <query>index=$case_tok$ host=$host_tok$ mitre_technique!=- mitre_technique=$mitre_tok$ logtype=service | `MITRE_lookup` "
        )
        t1055xml.write(
            '| search id="T1055" | table index host mitre_id mitre_technique Service Description | fillnull value=-</query>\n          <earliest>$time_tok.earliest$</earliest>\n          <latest>$time_tok.latest$</latest>\n          <sampleRatio>1</sampleRatio>\n          <progress>\n            <condition match="\'job.resultCount\' > 0">\n              <set token="t1055_unix_svc_panel">true</set>\n            </condition>\n            <condition>\n              <unset token="t1055_unix_svc_panel"/>\n            </condition>\n          </progress>\n        </search>\n        <option name="count">5</option>\n        <option name="dataOverlayMode">none</option>\n        <option name="drilldown">none</option>\n        <option name="percentagesRow">false</option>\n        <option name="rowNumbers">false</option>\n        <option name="totalsRow">false</option>\n        <option name="wrap">false</option>\n      </table>\n    '
        )
        t1055xml.write("</panel>\n  </row>\n</form>")
