#!/usr/bin/env python3 -tt
# memory-based IOCs - DO NOT EDIT THIS FILE
def create_local_transforms(transformsconf):
    start, prefix, suffix, end = "if(match(", ',"(', ')"), "', '", '
    assignment_pairings = {
        "ForeignPort_|_^110|143|465|993|995$": "T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.003 - Mail Protocols",  # memory
        "ForeignPort_|_^135$": "T1047.000 - Windows Management Instrumentation | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol",  # memory
        "ForeignPort_|_^137$": "T1187.000 - Forced Authentication | T1557.001 - LLMNR/NBT-NS Poisoning and SMB Relay",  # memory
        "ForeignPort_|_^139$": "T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1133.000 - External Remote Services | T1187.000 - Forced Authentication",  # memory
        "ForeignPort_|_^20|21$": "T1041.000 - Exfiltration over C2 Channel | T1071.002 - File Transfer Protocols | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol",  # memory
        "ForeignPort_|_^22|23$": "T1021.004 - SSH | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1133.000 - External Remote Services",  # memory
        "ForeignPort_|_^2375|2376$": "T1612.000 - Build Image on Host",  # memory
        "ForeignPort_|_^25$": "T1041.000 - Exfiltration over C2 Channel | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.003 - Mail Protocols",  # memory
        "ForeignPort_|_^3389$": "T1021.001 - Remote Desktop Protocol | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1210.000 - Exploitation of Remote Services",  # memory
        "ForeignPort_|_^389|88|1433|1521|3306$": "T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing",  # memory
        "ForeignPort_|_^443$": "T1041.000 - Exfiltration over C2 Channel  | T1048.001 - Exfiltration Over Symmetric Encrypted Non-C2 Protocol | T1048.002 - Exfiltration Over Asymmetric Encrypted Non-C2 Protocol | T1071.001 - Web Protocols | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1187.000 - Forced Authentication | T1189.000 - Drive-by Compromise",  # memory
        "ForeignPort_|_^445$": "T1021.002 - SMB/Windows Admin Shares | T1041.000 - Exfiltration over C2 Channel | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1133.000 - External Remote Services | T1187.000 - Forced Authentication | T1210.000 - Exploitation of Remote Services",  # memory
        "ForeignPort_|_^53$": "T1041.000 - Exfiltration over C2 Channel | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.002 - DNS",  # memory
        "ForeignPort_|_^5355$": "T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1557.001 - LLMNR/NBT-NS Poisoning and SMB Relay",  # memory
        "ForeignPort_|_^5800|5895|5938|5984|5986|8200$": "T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1219.000 - Remote Access Software",  # memory
        "ForeignPort_|_^5900$": "T1021.005 - VNC | T1219.000 - Remote Access Software | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol",  # memory
        "ForeignPort_|_^69|989|990$": "T1071.002 - File Transfer Protocols | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol",  # memory
        "ForeignPort_|_^80$": "T1041.000 - Exfiltration over C2 Channel | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.001 - Web Protocols | T1110.004 - Credential Stuffing | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1187.000 - Forced Authentication | T1189.000 - Drive-by Compromise",  # memory
        "LocalPort_|_^110|143|465|993|995$": "T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.003 - Mail Protocols",  # memory
        "LocalPort_|_^135$": "T1047.000 - Windows Management Instrumentation | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol",  # memory
        "LocalPort_|_^137$": "T1187.000 - Forced Authentication | T1557.001 - LLMNR/NBT-NS Poisoning and SMB Relay",  # memory
        "LocalPort_|_^139$": "T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1133.000 - External Remote Services | T1187.000 - Forced Authentication",  # memory
        "LocalPort_|_^20|21$": "T1041.000 - Exfiltration over C2 Channel | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.002 - File Transfer Protocols",  # memory
        "LocalPort_|_^22|23$": "T1021.004 - SSH | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1133.000 - External Remote Services",  # memory
        "LocalPort_|_^2375|2376$": "T1612.000 - Build Image on Host",  # memory
        "LocalPort_|_^25$": "T1041.000 - Exfiltration over C2 Channel | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.003 - Mail Protocols",  # memory
        "LocalPort_|_^3389$": "T1021.001 - Remote Desktop Protocol | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1210.000 - Exploitation of Remote Services",  # memory
        "LocalPort_|_^389|88|1433|1521|3306$": "T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing",  # memory
        "LocalPort_|_^443$": "T1041.000 - Exfiltration over C2 Channel  | T1048.001 - Exfiltration Over Symmetric Encrypted Non-C2 Protocol | T1048.002 - Exfiltration Over Asymmetric Encrypted Non-C2 Protocol | T1071.001 - Web Protocols | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1187.000 - Forced Authentication | T1189.000 - Drive-by Compromise",  # memory
        "LocalPort_|_^445$": "T1021.002 - SMB/Windows Admin Shares | T1041.000 - Exfiltration over C2 Channel | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1133.000 - External Remote Services | T1187.000 - Forced Authentication | T1210.000 - Exploitation of Remote Services",  # memory
        "LocalPort_|_^53$": "T1041.000 - Exfiltration over C2 Channel | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.002 - DNS",  # memory
        "LocalPort_|_^5355$": "T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1557.001 - LLMNR/NBT-NS Poisoning and SMB Relay",  # memory
        "LocalPort_|_^5800|5895|5938|5984|5986|8200$": "T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1219.000 - Remote Access Software",  # memory
        "LocalPort_|_^5900$": "T1021.005 - VNC | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1219.000 - Remote Access Software",  # memory
        "LocalPort_|_^69|989|990$": "T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.002 - File Transfer Protocols",  # memory
        "LocalPort_|_^80$": "T1041.000 - Exfiltration over C2 Channel | T1048.003 - Exfiltration over Unencrypted/Obfuscated Non-C2 Protocol | T1071.001 - Web Protocols | T1110.001 - Password Guessing | T1110.003 - Password Spraying | T1110.004 - Credential Stuffing | T1187.000 - Forced Authentication | T1189.000 - Drive-by Compromise",  # memory
    }
    transformsconf.write("[mitre_assign]\nINGEST_EVAL = local_mitre_techniques=")
    for ioc, mitre in assignment_pairings.items():
        transformsconf.write(
            "{}{}{}{}{}{}{}".format(
                start,
                ioc.split("_|_")[0],
                prefix,
                ioc.split("_|_")[1],
                suffix,
                mitre,
                end,
            )
        )
    transformsconf.write('"-"))))))))))))))))))))))))))))))))))), ')
    transformsconf.write('local_mitre_technique=split(local_mitre_techniques," | ")\n\n')


##ForeignPort_|_^NEGATE_STANDARD_PORTS_-_(ALL_PORTS_LISTED_ABOVE)$": "T1571.00 - Non-Standard Port
##LocalPort_|_^NEGATE_STANDARD_PORTS_-_(ALL_PORTS_LISTED_ABOVE)$": "T1571.00 - Non-Standard Port
